name: xeus-cling
channels:
  - conda-forge
  - gouarin
  - QuantStack
dependencies:
  - xeus-cling=0.8.1
  - xtensor 
  - xtensor-blas 
  - notebook
  - xwidgets  
  - xplot
  - bqplot 
  - widgetsnbextension 
